# Generated by Django 5.0.6 on 2024-05-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_on_home', models.BooleanField(default=False)),
                ('camera_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_environment', to='environment.cameraenvironment', verbose_name='Camera environment')),
            ],
        ),
    ]
