# Generated by Django 5.0.6 on 2024-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.IntegerField(max_length=5),
        ),
    ]
